variable "cluster_name" {}
variable "cluster_version" {}
variable "cluster_role_arn" {}
variable "node_role_arn" {}
variable "subnet_ids" {}
variable "desired_capacity" {}
variable "max_capacity" {}
variable "min_capacity" {}
variable "node_instance_type" {}
